- hosts: app
  sudo: yes

  tasks:
  - name: Install Required Dependencies For NodeJS
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs-legacy
      - nginx

  - name: Install pm2
    npm: name=pm2 global=yes production=yes

  - name: Check NPM is installed
    npm: path=/home/ubuntu/app
    register: npm_finished

  - name: ensure nginx is at the latest version
    apt: name=nginx state=latest

  - file: path=/etc/nginx/sites-enabled/default state=absent
 
  - name: Copy default file from app to nginx
    copy:
      src: /home/ubuntu/app/default
      dest: /etc/nginx/sites-enabled/default
      remote_src: yes
 
  - name: restart nginx
    service:
      name: nginx
      state: restarted






    
